/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/handv2.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0.18, 0.62, -0.32]} scale={0.19}>
        <primitive object={nodes.Bone} />
        <skinnedMesh geometry={nodes.Plane005.geometry} material={materials['Material #46']} skeleton={nodes.Plane005.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/handv2.gltf')
